# Generated by Django 4.0.3 on 2022-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=245)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
